#!/bin/bash
# chkconfig:   - 25 75
# description: carbon-relay
# processname: carbon-relay

export PYTHONPATH="$GRAPHITE_DIR/lib:$PYTHONPATH"

# Source function library.
if [ -e /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

DAEMON="relay"
GRAPHITE_DIR="/opt/graphite"
LOG_DIR="/var/log/graphite"
CONF="${GRAPHITE_DIR}/conf/carbon.conf"
INSTANCES=$(grep "^\[${DAEMON}" ${CONF} | cut -d \[ -f 2 | cut -d \] -f 1 | cut -d : -f 2)

function die {
  echo $1
  exit 1
}

start(){
    if [ ! -z $ONLY_INSTANCE ]; then
        echo "Starting carbon-${DAEMON}:${ONLY_INSTANCE}..."
        $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${ONLY_INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${ONLY_INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${ONLY_INSTANCE} --config=${CONF} start

        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi
        echo ""
    else
        for INSTANCE in ${INSTANCES}; do
            if [ "${INSTANCE}" == "${DAEMON}" ]; then
                INSTANCE="a"
            fi
            echo "Starting carbon-${DAEMON}:${INSTANCE}..."
            $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${INSTANCE} --config=${CONF} start

            if [ $? -eq 0 ]; then
                echo_success
            else
                echo_failure
            fi
            echo ""
        done
    fi
}

stop(){
    if [ ! -z $ONLY_INSTANCE ]; then
        echo "Stopping carbon-${CARBON_DAEMON}:${ONLY_INSTANCE}..."
        $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${ONLY_INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${ONLY_INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${ONLY_INSTANCE} --config=${CONF} stop
        sleep 20
        pid=$(/usr/bin/pgrep -f "carbon-${DAEMON}.py --instance=${ONLY_INSTANCE}")
        if [ ! -z $pid ]; then
            ports=$(/bin/netstat -lnp | grep "${pid}" | grep ":2.*" | /usr/bin/wc -l)
            if [ $ports -gt 0 ]; then
                echo "Instance ${ONLY_INSTANCE} did not release ports yet. Sleeping longer, then force killing it..."
                sleep 5
                /usr/bin/pkill -9 -f "carbon-${DAEMON}.py --instance=${ONLY_INSTANCE}"
            fi
        fi

        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi
        echo ""
    else
        for INSTANCE in ${INSTANCES}; do
            if [ "${INSTANCE}" == "${CARBON_DAEMON}" ]; then
                INSTANCE="a"
            fi
            echo "Stopping carbon-${DAEMON}:${INSTANCE}..."
            $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${INSTANCE} --config=${CONF} stop
            sleep 20
            pid=$(/usr/bin/pgrep -f "carbon-${DAEMON}.py --instance=${INSTANCE}")
            if [ ! -z $pid ]; then
                ports=$(/bin/netstat -lnp | grep "${pid}" | grep ":2.*" | /usr/bin/wc -l)
                if [ $ports -gt 0 ]; then
                    echo "Instance ${INSTANCE} did not release ports yet. Sleeping longer, then force killing it..."
                    sleep 5
                    /usr/bin/pkill -9 -f "carbon-${DAEMON}.py --instance=${INSTANCE}"
                fi
            fi

            if [ $? -eq 0 ]; then
                echo_success
            else
                echo_failure
            fi
            echo ""
        done
    fi
}

status(){
    if [ ! -z $ONLY_INSTANCE ]; then
        $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${ONLY_INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${ONLY_INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${ONLY_INSTANCE} --config=${CONF} status
    
        if [ $? -eq 0 ]; then
            echo_success
        else
            echo_failure
        fi
        echo ""
    else
        for INSTANCE in ${INSTANCES}; do
            if [ "${INSTANCE}" == "${DAEMON}" ]; then
                INSTANCE="a"
            fi
            $GRAPHITE_DIR/bin/carbon-${DAEMON}.py --instance=${INSTANCE} --pidfile=$LOG_DIR/${DAEMON}-${INSTANCE}/carbon-${DAEMON}.pid --logdir=$LOG_DIR/${DAEMON}_${INSTANCE} --config=${CONF} status
    
            if [ $? -eq 0 ]; then
                echo_success
            else
                echo_failure
            fi
            echo ""
        done
    fi
}

if [ -n $2 ]; then
    ONLY_INSTANCE=$2
fi

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status} ({instance})"
    exit 1
esac
